version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dependabot/build-deps"
    labels:
      - "dependencies"
      - "build-deps"
