services:
  source:
    image: pythonph/pythonph
    volumes:
      - /usr/src/app/.venv
      - /usr/src/app/staticfiles
    environment:
      - APP_ENV=development
    env_file: dev.env
    command: bin/install

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=pythonph
    env_file: dev.env

  web:
    image: pythonph/pythonph
    volumes_from:
      - source
    environment:
      - APP_ENV=development
    env_file: dev.env
    ports:
      - 8000:8000
    depends_on:
      - db
    command: gunicorn -b 0.0.0.0:8000 --access-logfile - --error-logfile - config.wsgi:application

  nginx:
    build: nginx
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - web
