services:
  source:
    image: pythonph/pythonph
    volumes:
      - /usr/src/app/.venv
      - /usr/src/app/staticfiles
    environment:
      - APP_ENV=production
    env_file: prod.env
    command: bin/install

  web:
    image: pythonph/pythonph
    volumes_from:
      - source
    environment:
      - APP_ENV=production
    env_file: prod.env
    command: gunicorn -b 0.0.0.0:8000 --access-logfile - --error-logfile - config.wsgi:application

  nginx:
    build: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
