services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=pythonph
    env_file: dev.env

  web:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV=development
      - DATABASE_URL=postgres://pythonph:pythonph@db:5432/pythonph
    env_file: dev.env
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
