# Generated by Django 6.0.7 on 2026-08-08 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('display_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('commitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='organisation.commitee')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
