# Generated by Django 6.0.7 on 2026-08-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='commitee_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('co_lead', 'Co-Lead'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
