# Generated by Django 6.0.7 on 2026-08-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
