# Generated by Django 6.0.7 on 2026-08-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
