# Generated by Django 2.2.18 on 2021-03-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
