# Generated by Django 6.0.7 on 2026-08-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
