"""Auth admin registrations.

Django's stock ``UserAdmin``/``GroupAdmin`` subclass the plain admin
``ModelAdmin``, which lacks unfold's ``show_add_link`` attribute. Unfold's
changelist template hides the add button for such admins, so the Users and
Groups pages render without one. Mixing in ``unfold.admin.ModelAdmin`` restores
the button (and the unfold look) without changing auth behaviour.
"""

import string

from django import forms
from django.contrib import admin, messages
from django.contrib.auth.admin import GroupAdmin as BaseGroupAdmin
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.forms import AdminUserCreationForm
from django.contrib.auth.models import Group, User
from django.utils.crypto import get_random_string
from unfold.admin import ModelAdmin as UnfoldModelAdmin

admin.site.unregister(Group)
admin.site.unregister(User)


class UserAdminCreationForm(AdminUserCreationForm):
    """Add-user form that captures identity fields up front."""

    autogenerate_password = forms.BooleanField(
        required=False,
        label="Autogenerate password",
        help_text=(
            "Generate a random password, set it on the account and show it once "
            "after saving. The password fields below are ignored."
        ),
    )

    class Meta(AdminUserCreationForm.Meta):
        model = User
        fields = ("username", "first_name", "last_name", "email")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.data and self.data.get("autogenerate_password"):
            self.fields["password1"].required = False
            self.fields["password2"].required = False

    def validate_passwords(
        self,
        password1_field_name="password1",
        password2_field_name="password2",
        usable_password_field_name="usable_password",
    ):
        if self.cleaned_data.get("autogenerate_password"):
            # A generated password is always usable, so ignore the
            # "Password-based authentication" radio when autogenerating.
            self.cleaned_data[usable_password_field_name] = "true"
            password = get_random_string(length=16, allowed_chars=string.ascii_letters + string.digits)
            self.cleaned_data[password1_field_name] = password
            self.cleaned_data[password2_field_name] = password
            self.generated_password = password
        super().validate_passwords(
            password1_field_name,
            password2_field_name,
            usable_password_field_name,
        )


@admin.register(User)
class UserAdmin(BaseUserAdmin, UnfoldModelAdmin):
    add_form = UserAdminCreationForm

    class Media:
        js = ("js/autogenerate_password.js",)

    add_fieldsets = (
        (
            None,
            {
                "classes": ("wide",),
                "fields": (
                    "username",
                    "first_name",
                    "last_name",
                    "email",
                    "autogenerate_password",
                    "usable_password",
                    "password1",
                    "password2",
                ),
            },
        ),
    )

    def save_model(self, request, obj, form, change):
        super().save_model(request, obj, form, change)
        password = getattr(form, "generated_password", None)
        if password:
            messages.add_message(
                request,
                messages.SUCCESS,
                "User created with autogenerated password: %s — share it with "
                "the user now, it will not be shown again." % password,
            )


@admin.register(Group)
class GroupAdmin(BaseGroupAdmin, UnfoldModelAdmin):
    pass
