import re

from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse

PASSWORD = "Str0ng!Passw0rd"


class AuthChangelistAddButtonTests(TestCase):
    """Unfold only renders the changelist add button for admins that set
    ``show_add_link`` (see ``unfold/helpers/add_link.html``). Django's stock
    User/Group admins don't, so the unfold mixins in ``app.accounts.admin``
    must keep the button visible."""

    @classmethod
    def setUpTestData(cls):
        cls.admin = User.objects.create_superuser(
            username="admin",
            email="admin@example.com",
            password="password",
        )

    def test_user_changelist_shows_add_button(self):
        self.client.force_login(self.admin)
        response = self.client.get(reverse("admin:auth_user_changelist"))
        self.assertContains(response, reverse("admin:auth_user_add"))

    def test_group_changelist_shows_add_button(self):
        self.client.force_login(self.admin)
        response = self.client.get(reverse("admin:auth_group_changelist"))
        self.assertContains(response, reverse("admin:auth_group_add"))

    def test_user_add_form_includes_identity_fields(self):
        """The admin add-user form must capture email, first and last name at
        creation time, not just username and passwords."""
        self.client.force_login(self.admin)
        response = self.client.get(reverse("admin:auth_user_add"))
        for field_name in ("email", "first_name", "last_name"):
            self.assertContains(response, f'name="{field_name}"')

    def test_user_add_form_saves_identity_fields(self):
        self.client.force_login(self.admin)
        response = self.client.post(
            reverse("admin:auth_user_add"),
            {
                "username": "juan",
                "first_name": "Juan",
                "last_name": "Dela Cruz",
                "email": "juan@example.com",
                "password1": "Str0ng!Passw0rd",
                "password2": "Str0ng!Passw0rd",
            },
        )
        self.assertRedirects(response, reverse("admin:auth_user_change", args=[User.objects.latest("pk").pk]))
        user = User.objects.get(username="juan")
        self.assertEqual(user.first_name, "Juan")
        self.assertEqual(user.last_name, "Dela Cruz")
        self.assertEqual(user.email, "juan@example.com")

    def test_user_add_form_has_autogenerate_option(self):
        self.client.force_login(self.admin)
        response = self.client.get(reverse("admin:auth_user_add"))
        self.assertContains(response, 'name="autogenerate_password"')

    def test_user_add_autogenerate_password_creates_usable_user(self):
        """With the autogenerate option checked, a random usable password is
        set and shown once in the success message."""
        self.client.force_login(self.admin)
        response = self.client.post(
            reverse("admin:auth_user_add"),
            {
                "username": "auto",
                "first_name": "Auto",
                "last_name": "Gen",
                "email": "auto@example.com",
                "autogenerate_password": "on",
            },
            follow=True,
        )
        user = User.objects.get(username="auto")
        self.assertTrue(user.has_usable_password())
        match = re.search(r"autogenerated password: (\S+)", response.content.decode())
        self.assertIsNotNone(match, "success message with the generated password missing")
        self.assertTrue(user.check_password(match.group(1)))


class UserPasswordChangeTests(TestCase):
    """The user change form must expose a password edit link (the Unfold
    widget override in ``templates/auth/widgets/`` restores it) and the
    password change view must update the stored hash."""

    @classmethod
    def setUpTestData(cls):
        cls.admin = User.objects.create_superuser(
            username="admin",
            email="admin@example.com",
            password="password",
        )
        cls.user = User.objects.create_user(
            username="juan",
            email="juan@example.com",
            password=PASSWORD,
        )

    def test_change_form_shows_password_link(self):
        self.client.force_login(self.admin)
        response = self.client.get(reverse("admin:auth_user_change", args=[self.user.pk]))
        self.assertContains(response, "Reset password")
        self.assertContains(response, "../password/")

    def test_change_form_shows_set_password_link_for_passwordless_user(self):
        self.client.force_login(self.admin)
        user = User.objects.create_user(username="nopw", email="nopw@example.com")
        response = self.client.get(reverse("admin:auth_user_change", args=[user.pk]))
        self.assertContains(response, "Set password")

    def test_password_change_updates_password(self):
        self.client.force_login(self.admin)
        response = self.client.post(
            reverse("admin:auth_user_password_change", args=[self.user.pk]),
            {"password1": "New!Passw0rd", "password2": "New!Passw0rd"},
        )
        self.assertRedirects(response, reverse("admin:auth_user_change", args=[self.user.pk]))
        self.user.refresh_from_db()
        self.assertTrue(self.user.check_password("New!Passw0rd"))
        self.assertFalse(self.user.check_password(PASSWORD))
